# quickstart environment for healthcare-hl7-xml

services:
  healthcare-hl7-xml:
    init: true
    build:
      context: .
      dockerfile: Dockerfile
    image: healthcare-hl7-xml:dev
    container_name: healthcare-hl7-xml
    ports:
    - 1972:1972
    - 52773:52773
    volumes:
    - .:/app
