version: '3.2'

services:
  # development environment for healthcare-hl7-xml
  hl7xml:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: hl7xml
    ports:
    - "51773:51773"
    - "52773:52773"
    volumes:
    - .:/app